analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    deprecated_member_use: ignore
linter:
  rules:
    sort_constructors_first: true
    unnecessary_await_in_return: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    public_member_api_docs: false